spring.config.import=optional:file:.env.local.example[.properties]

server.port=8083
spring.application.name=notification-service

application.log-file-path=logs

#DataSource
spring.datasource.host=${DB_HOST}
spring.datasource.port=${DB_PORT}
spring.datasource.db-name=${DB_NAME}
spring.datasource.url=jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.db-name}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.entity-packages=ru.mentor.entity
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

#Cors
application.cors.origins=*
application.cors.methods=*
application.cors.headers=*

#Auth
microservice.auth-key=${NOTIFICATION_API_KEY}

#security / tracing
grpc.common.api-key=${NOTIFICATION_API_KEY:}
grpc.common.node-id=${NOTIFICATION_NODE_ID:}

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=learningplatform0808@gmail.com
spring.mail.password=mcxy afju qnug fhgj
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
application.notify.email.enable=true

#Telegram Configuration
application.notify.telegram.enable=false

#Kafka
spring.kafka.consumer.bootstrap-servers=${KAFKA_HOST}
spring.kafka.consumer.group-id=${KAFKA_GROUP_ID}
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.value.default.type=ru.mentor.dto.kafka.KafkaNotificationDto
spring.kafka.consumer.properties.spring.json.use.type.headers=false

#Cache
cache.notification.template.update.interval.cron=0 */5 * * * *