server.port=8083
spring.application.name=notification-service

application.log-file-path=logs

#DataSource
spring.datasource.host=${DB_HOST:database}
spring.datasource.port=${DB_PORT:5432}
spring.datasource.db-name=${DB_NAME:mentor}
spring.datasource.url=jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.db-name}
spring.datasource.username=${DB_USERNAME:user}
spring.datasource.password=${DB_PASSWORD:psw}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.entity-packages=ru.mentor.entity
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

#Cors
application.cors.origins=*
application.cors.methods=*
application.cors.headers=*

#Auth
microservice.auth-key=${NOTIFICATION_API_KEY:NOTIFICATION_SERVICE_SECRET_KEY_123}

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=learningplatform0808@gmail.com
spring.mail.password=mcxy afju qnug fhgj
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
application.notify.email.enable=true

#Telegram Configuration
application.notify.telegram.enable=false

#Kafka
spring.kafka.consumer.bootstrap-servers=${KAFKA_HOST:127.0.0.1:9092}
spring.kafka.consumer.group-id=${KAFKA_GROUP_ID:notification-events}

#Cache
cache.notification.template.update.interval.min=5