services:
  common-lib:
    profiles:
      - lib.build
    build:
      context: .
      dockerfile: ./reactive-common-lib/Dockerfile
    image: mentor/common-lib:local

  api-gateway:
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    env_file:
      - .env.docker.example
    container_name: api-gateway
    image: mentor/api-gateway:local
    ports:
      - "8080:8080"
    networks:
      - public
      - backend
    depends_on:
      - database
      - kafka-1

  course-service:
    build:
      context: .
      dockerfile: ./course-service/Dockerfile
    env_file:
      - .env.docker.example
    container_name: course-service
    image: mentor/course-service:local
    ports:
      - "8081:8081"
    networks:
      - backend
    depends_on:
      - database
      - kafka-1

  mentor-service:
    build:
      context: .
      dockerfile: ./mentor-service/Dockerfile
    env_file:
      - .env.docker.example
    container_name: mentor-service
    image: mentor/mentor-service:local
    ports:
      - "8082:8082"
    networks:
      - backend
    depends_on:
      - database
      - kafka-1

  notification-service:
    build:
      context: .
      dockerfile: ./notification-service/Dockerfile
    env_file:
      - .env.docker.example
    container_name: notification-service
    image: mentor/notification-service:local
    ports:
      - "8083:8083"
    networks:
      - backend
    depends_on:
      - database
      - kafka-1

  calendar-service:
    build:
      context: .
      dockerfile: ./calendar-service/Dockerfile
    env_file:
      - .env.docker.example
    container_name: calendar-service
    image: mentor/calendar-service:local
    ports:
      - "8084:8084"
    networks:
      - backend
    depends_on:
      - database
      - kafka-1

  admin-service:
    build:
      context: .
      dockerfile: ./admin-service/Dockerfile
    env_file:
      - .env.docker.example
    container_name: admin-service
    image: mentor/admin-service:local
    ports:
      - "8085:8085"
    networks:
      - backend
    depends_on:
      - database
      - kafka-1

  database:
    container_name: mentor-database
    image: postgres:15.3-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: psw
      POSTGRES_DB: mentor
    volumes:
      - mentor-database:/var/lib/postgres/data
    networks:
      - backend

  kafka-1:
    env_file:
      - .env.docker.example
    image: apache/kafka:3.9.1
    ports:
      - "9092:9092"
    networks:
      - backend

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8086:8080"
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka-1:9092
    networks:
      - public
      - backend
    depends_on:
      - kafka-1

volumes:
  mentor-database:
    name: mentor-database

networks:
  backend:
    name: backend
    driver: bridge
  public:
    name: public
    driver: bridge
