set -e
if [ -f ".env.docker.example" ]; then
  cp -f .env.docker.example .env
fi
echo "--"
echo "----"
echo "------"
echo "--------"
echo "----------"
echo "--"
echo "----"
echo "------"
echo "--------"
echo "----------"
echo "------------ НАЧАЛО СБОРКИ ВСЕХ МИКРОСЕРВИСОВ..."
echo "----------"
echo "--------"
echo "------"
echo "----"
echo "--"
docker compose build
echo "--"
echo "----"
echo "------"
echo "--------"
echo "----------"
echo "------------ СБОРКА ОБРАЗОВ ВСЕХ МИКРОСЕРВИСОВ ЗАВЕРШЕНА!"
echo "----------"
echo "--------"
echo "------"
echo "----"
echo "--"
echo "--"
echo "----"
echo "------"
echo "--------"
echo "----------"
echo "------------ ЗАПУСК ВСЕХ МИКРОСЕРВИСОВ И ИНФРАСТРУКТУРЫ В КОНТЕЙНЕРАХ..."
echo "----------"
echo "--------"
echo "------"
echo "----"
echo "--"
docker compose up -d
echo "--"
echo "----"
echo "------"
echo "--------"
echo "----------"
echo "------------ ВСЕ МИКРОСЕРВИСЫ И ИНФРАСТРУКТУРА ЗАПУЩЕНЫ!"
echo "----------"
echo "--------"
echo "------"
echo "----"
echo "--"