server.port=8086
spring.application.name=calendar-service

application.log-file-path=logs

#DataSource
spring.datasource.host=${DB_HOST:database}
spring.datasource.port=${DB_PORT:5432}
spring.datasource.db-name=${DB_NAME:mentor}
spring.datasource.url=jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.db-name}
spring.datasource.username=${DB_USERNAME:user}
spring.datasource.password=${DB_PASSWORD:psw}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.entity-packages=ru.mentor.entity
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

#Cors
application.cors.origins=*
application.cors.methods=*
application.cors.headers=*

#Kafka
spring.kafka.producer.bootstrap-servers=${KAFKA_HOST:localhost:9093}
spring.kafka.producer.properties.delivery.timeout.ms=10000
spring.kafka.producer.properties.delivery.lingerms=5000
spring.kafka.producer.properties.request.timeout.ms=5000
spring.kafka.producer.properties.max.in.flight.requests.per.connection=5
spring.kafka.producer.properties.security.protocol=PLAINTEXT
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.acks=0

#grpc
grpc.server.port=6567
grpc.server.security.enabled=false