server.port=8081
spring.application.name=mentor-service
#spring.config.import=file:.env[.properties]

application.log-file-path=logs

#DataSource
spring.datasource.host=${DB_HOST:localhost}
spring.datasource.port=${DB_PORT:5433}
spring.datasource.db-name=${DB_NAME:mentor}
spring.datasource.url=jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.db-name}
spring.datasource.username=${DB_USERNAME:user}
spring.datasource.password=${DB_PASSWORD:psw}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.entity-packages=ru.mentor.entity
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

token.signing.key= PVU+sMExaAa9l8uddkUPpDT+EvcZA/hlasmXRUT9ChM=
token.access.expiration.minutes= 15
token.refresh.expiration.day= 15

#Cors
application.cors.origins=*
application.cors.methods=*
application.cors.headers=*

#Integration
integration.course-service.url=${COURSE_SERVICE_URL:localhost:8082}
integration.course-service.api-key= ${COURSE_API_KEY:COURSE_SERVICE_SECRET_KEY_123}
integration.access-service.url=${MENTOR_SERVICE_URL:localhost:8083}
integration.access-service.api-key= ${ACCESS_API_KEY:ACCESS_SERVICE_SECRET_KEY_123}
feign.client.retry.maxAttempts= ${CLIENT_RETRY_MAX_ATTEMPTS:3}
feign.client.retry.period= ${CLIENT_RETRY_PERIOD:1000}
feign.client.retry.maxPeriod= ${CLIENT_RETRY_MAX_PERIOD:10000}