spring.config.import=optional:file:.env.local.example[.properties]

management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true

server.port=8080
spring.application.name=api-gateway

application.log-file-path=logs

#DataSource
spring.datasource.host=${DB_HOST}
spring.datasource.port=${DB_PORT}
spring.datasource.db-name=${DB_NAME}
spring.datasource.url=jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.db-name}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.entity-packages=ru.mentor.entity
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db.changelog/db.changelog-master.xml
spring.liquibase.url=jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.db-name}
spring.liquibase.user=${DB_USERNAME}
spring.liquibase.password=${DB_PASSWORD}

spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

token.signing.key= PVU+sMExaAa9l8uddkUPpDT+EvcZA/hlasmXRUT9ChM=
token.access.expiration.minutes= 15
token.refresh.expiration.day= 15

#Cors
application.cors.origins=*
application.cors.methods=*
application.cors.headers=*

#Integration
integration.course-service.url=${COURSE_SERVICE_URL}
integration.course-service.api-key= ${COURSE_API_KEY}
integration.access-service.url=${MENTOR_SERVICE_URL}
integration.access-service.api-key= ${ACCESS_API_KEY}
feign.client.retry.maxAttempts= ${CLIENT_RETRY_MAX_ATTEMPTS}
feign.client.retry.period= ${CLIENT_RETRY_PERIOD}
feign.client.retry.maxPeriod= ${CLIENT_RETRY_MAX_PERIOD}

#grpc
grpc.retry.max-attempts=3
grpc.retry.delay=3
grpc.client.calendar-service-client.address=${CALENDAR_REDIRECTION_GRPC}
grpc.client.calendar-service-client.negotiation-type=plaintext

grpc.client.admin-calendar-client.address=${ADMIN_CALENDAR_GRPC_CLIENT}
grpc.client.admin-calendar-client.negotiation-type=plaintext

grpc.client.admin-module-client.address=${ADMIN_MODULE_GRPC_CLIENT}
grpc.client.admin-module-client.negotiation-type=plaintext

grpc.client.admin-course-client.address=${ADMIN_COURSE_GRPC_CLIENT}
grpc.client.admin-course-client.negotiation-type=plaintext

grpc.client.course-client.address=${COURSE_REDIRECTION_GRPC}
grpc.client.course-client.negotiation-type=plaintext

grpc.client.module-client.address=${MODULE_GRPC_CLIENT}
grpc.client.module-client.negotiation-type=plaintext

# Kafka
spring.kafka.producer.bootstrap-servers=${KAFKA_HOST}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

#security / tracing
grpc.common.api-key=${API_GATEWAY_API_KEY:}
grpc.common.node-id=${API_GATEWAY_NODE_ID:}


