spring.config.import=optional:file:.env.local.example[.properties]

spring.main.web-application-type=none

# Netty
server.port=8081
spring.application.name=course-service

application.log-file-path=logs

# DataSource
spring.r2dbc.host=${DB_HOST}
spring.r2dbc.port=${DB_PORT}
spring.r2dbc.database=${DB_NAME}
spring.r2dbc.username=${DB_USERNAME}
spring.r2dbc.password=${DB_PASSWORD}
spring.r2dbc.url=r2dbc:postgresql://${spring.r2dbc.host}:${spring.r2dbc.port}/${spring.r2dbc.database}


#Cors
application.cors.origins=*
application.cors.methods=*
application.cors.headers=*

#Auth
microservice.auth-key=${COURSE_API_KEY}

#security / tracing
grpc.common.api-key=${COURSE_API_KEY:}
grpc.common.node-id=${COURSE_NODE_ID:}

#Kafka
spring.kafka.producer.bootstrap-servers=${KAFKA_HOST}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

#Grpc
grpc.server.port=1081
grpc.server.security.enabled=false