server.port=8081
spring.application.name=course-service
spring.config.import=file:.env[.properties]

application.log-file-path=logs

#DataSource
application.datasource.host=${DB_HOST}
application.datasource.port=${DB_PORT}
application.datasource.db-name=${DB_NAME}
application.datasource.jdbc-url=jdbc:postgresql://${application.datasource.host}:${application.datasource.port}/${application.datasource.db-name}
application.datasource.username=${DB_USERNAME}
application.datasource.password=${DB_PASSWORD}
application.datasource.schema=${DB_SCHEMA}
application.datasource.driver-class-name=org.postgresql.Driver
application.datasource.entity-packages=ru.mentor.entity

spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

#Cors
application.cors.origins=*
application.cors.methods=*
application.cors.headers=*