spring.config.import=optional:file:.env.local.example[.properties]

server.port=8081
spring.application.name=course-service

# gRPC server configuration
grpc.server.port=1081
grpc.server.security.enabled=false

application.log-file-path=logs

#DataSource
spring.datasource.host=${DB_HOST}
spring.datasource.port=${DB_PORT}
spring.datasource.db-name=${DB_NAME}
spring.datasource.url=jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.db-name}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.entity-packages=ru.mentor.entity
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

#Cors
application.cors.origins=*
application.cors.methods=*
application.cors.headers=*

#Auth
microservice.auth-key=${COURSE_API_KEY}

#security / tracing
security.api-key=${COURSE_API_KEY:api-key}
service.node-id=${COURSE_NODE_ID:node-id}

#Kafka
spring.kafka.producer.bootstrap-servers=${KAFKA_HOST}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer