server.port=8082
spring.application.name=mentor-service

application.log-file-path=logs

#DataSource
spring.datasource.host=${DB_HOST:localhost}
spring.datasource.port=${DB_PORT:5433}
spring.datasource.db-name=${DB_NAME:mentor}
spring.datasource.url=jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.db-name}
spring.datasource.username=${DB_USERNAME:user}
spring.datasource.password=${DB_PASSWORD:psw}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.entity-packages=ru.mentor.entity
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

#Cors
application.cors.origins=*
application.cors.methods=*
application.cors.headers=*

#Auth
microservice.auth-key=${ACCESS_API_KEY:ACCESS_SERVICE_SECRET_KEY_123}

#Integration
integration.notification-service.url:${NOTIFICATION_SERVICE_URL:localhost:8083}
integration.notification-service.api-key: ${NOTIFICATION_API_KEY:NOTIFICATION_SERVICE_SECRET_KEY_123}

#Kafka
spring.kafka.producer.bootstrap-servers=${KAFKA_HOST:127.0.0.1:9092}
spring.kafka.producer.properties.delivery.timeout.ms=10000
spring.kafka.producer.properties.delivery.lingerms=5000
spring.kafka.producer.properties.request.timeout.ms=5000
spring.kafka.producer.properties.max.in.flight.requests.per.connection=5
spring.kafka.producer.properties.security.protocol=PLAINTEXT
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.acks=all

logging.level.org.apache.kafka=OFF
logging.level.kafka=OFF
logging.level.org.springframework.kafka=OFF