INSERT INTO course_tags (tag_name)
VALUES ('backend'),
       ('frontend'),
       ('java'),
       ('react'),
       ('system analysis'),
       ('database'),
       ('devops'),
       ('mobile'),
       ('testing'),
       ('security'),
       ('cloud'),
       ('machine learning'),
       ('data science'),
       ('algorithms'),
       ('python'),
       ('c++'),
       ('go'),
       ('kotlin'),
       ('swift'),
       ('php'),
       ('typescript'),
       ('javascript'),
       ('spring'),
       ('hibernate'),
       ('angular'),
       ('vue'),
       ('django'),
       ('flask'),
       ('node.js'),
       ('express'),
       ('design patterns')
    ON CONFLICT (tag_name) DO NOTHING;