{
 "title": "API-Gateway HTTP-requests",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "uri",
    "label": "Эндпойнт",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{application=\"api-gateway\"},uri)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Total RPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Общий RPS по выбранному эндпойнту(-ам)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"api-gateway\", uri=~\"$uri\"}[$__rate_interval])) by (uri)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Общий RPS (по всем эндпойнтам, статусам и HTTP-методам)",
   "type": "timeseries",
   "description": "Метрика http_server_requests_seconds_count - счётчик (counter), который считает общее количество обработанных HTTP-запросов с начала работы приложения. Функция rate() вычисляет среднюю скорость роста счётчика за указанный интервал времени (здесь 1m0s — одна минута). Функция sum() суммирует RPS всех эндпоинтов, всех методов, всех статусов ответа в один общий RPS для всего приложения. Итог: формула возвращает общее количество запросов в секунду, которое обрабатывает api-gateway, усреднённое за последнюю минуту (rate_interval).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"api-gateway\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Response status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "RPS успешных запросов (статус 2xx) по выбранному эндпойнту(-ам)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"api-gateway\", status=~\"2..\", uri=~\"$uri\"}[$__rate_interval])) by (uri)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS клиентских ошибок (статус 4xx) по выбранному эндпойнту(-ам)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"api-gateway\", status=~\"4..\", uri=~\"$uri\"}[$__rate_interval])) by (uri)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS серверных ошибок (статус 5xx) по выбранному эндпойнту(-ам)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"api-gateway\", status=~\"5..\", uri=~\"$uri\"}[$__rate_interval])) by (uri)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Общий RPS успешных запросов (статус 2xx)",
   "type": "timeseries",
   "description": "Показывает количество запросов в секунду с HTTP-статусами 2xx (успешные запросы), просуммированное по всем эндпойнтам и HTTP-методам. Итог: общий RPS успешных запросов для всего приложения, усредненный за rate_interval (1 мин).",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"2..\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Общий RPS клиентских ошибок (статус 4xx)",
   "type": "timeseries",
   "description": "Показывает количество запросов в секунду с HTTP-статусами, начинающимися на 4 (400, 401 и т.д., клиентские ошибки), просуммированное по всем эндпойнтам и HTTP-методам. Итог: общий RPS ошибок 4xx для всего приложения, усредненный за rate_interval (1 мин).",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"4..\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Общий RPS серверных ошибок (статус 5xx)",
   "type": "timeseries",
   "description": "Показывает количество запросов в секунду с HTTP-статусами 5xx (серверные ошибки), просуммированное по всем эндпойнтам и HTTP-методам. Итог: общий RPS ошибок 5xx для всего приложения, усредненный за rate_interval (1 мин).",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"5..\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Response time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Среднее время ответа в секундах",
   "type": "timeseries",
   "description": "Вычисляется как сумма времени ответов по выбранному эндпойнту, деленная на количество запросов к нему, за интервал (rate_interval=1 мин).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{uri=~\"$uri\"}[$__rate_interval])) by (uri) / sum(rate(http_server_requests_seconds_count{uri=~\"$uri\"}[$__rate_interval])) by (uri)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Максимальное время ответа в секундах",
   "type": "timeseries",
   "description": "Метрика http_server_requests_seconds_max содержит максимальное значение времени ответа на запрос к выбранному эндпойнту за временной интервал.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "max(http_server_requests_seconds_max{uri=~\"$uri\"}) by (uri)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}