spring.config.import=optional:file:.env.local.example[.properties]

spring.main.web-application-type=none

#DataSource
spring.r2dbc.host=${DB_HOST}
spring.r2dbc.port=${DB_PORT}
spring.r2dbc.database=${DB_NAME}
spring.r2dbc.username=${DB_USERNAME}
spring.r2dbc.password=${DB_PASSWORD}
spring.r2dbc.url=r2dbc:postgresql://${spring.r2dbc.host}:${spring.r2dbc.port}/${spring.r2dbc.database}

# WebFlux server configuration (Netty)
server.port=8085
server.netty.max-initial-line-length=8192
server.netty.max-header-size=8192

# gRPC server configuration
grpc.server.port=1085
grpc.server.security.enabled=false

# Отключаем SpringDoc
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

# security / tracing
security.api-key=${ADMIN_API_KEY:api-key}
service.node-id=${ADMIN_NODE_ID:node-id}